### ISSUE TITLE
Script names not saving in maps on Objects or Lights

### ISSUE THREAD

**Issue by gtshmeh** [Lambdarevolution/Red-dead-redemption-2-map-editor#23]
If you attach a chaiscript to an object or light and save the map, this is what saves in the map file:

![script-name-not-saved](https://user-images.githubusercontent.com/80655058/111866259-708ec000-8929-11eb-8a5e-fa40db086c98.png)

If you manually replace "script" in the XML with the script name and load the map, the map and scripts will load fine.  If you leave it as-is, you have bad times:

![crash-loading-map-lights-lightobjects](https://user-images.githubusercontent.com/80655058/111866310-cd8a7600-8929-11eb-888b-b4a3e3eec559.PNG)

**Comment by Lambdarevolution** [comment]
Fixed
