### ISSUE TITLE
Player Spawn points not active until one is manually created in current session

### ISSUE THREAD

**Issue by gtshmeh** [Lambdarevolution/Red-dead-redemption-2-map-editor#26]
If you load the game and load a map that contains a spawn point, the player will not be teleported.  If you create a spawn point anywhere (New Map>Set Player Spawn), and then load any map with a spawn point, the player will now teleport successfully.

**Comment by Lambdarevolution** [comment]
This is not a valid issue setting UnloadMapsOnLoad to true will activate the spawn point
