### ISSUE TITLE
UI - Wrong values display in Position y and z fields when moving an object

### ISSUE THREAD

**Issue by gtshmeh** [Lambdarevolution/Red-dead-redemption-2-map-editor#29]
When you are editing the XYZ position  of an object, the fields for Y and Z will actually inherit the value of the Position X field.  If you click Accept Settings and then select the object again, the values will update to the correct numbers (until you press left or right arrow to edit them again).

**Comment by gtshmeh** [comment]
![object-position](https://user-images.githubusercontent.com/80655058/112598061-47f44380-8dcb-11eb-8747-02a7cc499ed0.png)
(example)

**Comment by Lambdarevolution** [comment]
Solved
